Vagrant.configure("2") do |config|

  config.vm.define "first" do |first|
    first.vm.box = "bento/ubuntu-20.04"
    first.vm.network "public_network", bridge: "enp3s0"
  end

  config.vm.define "second" do |second|
    second.vm.box = "bento/ubuntu-20.04"
    second.vm.network "public_network", bridge: "enp3s0"
  end
end
